repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version available
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer    # Ensures the file ends with a newline
      - id: check-yaml           # Checks YAML file syntax
  - repo: https://github.com/psf/black
    rev: 23.1a1  # You can specify any version you want
    hooks:
      - id: black  # Automatically formats Python code using Black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Replace with the Mypy version you use
    hooks:
      - id: mypy  # Static type checker for Python
