# version: "3.8"  # Remove or comment out this line
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db

  fastapi:
    build: .
    container_name: fastapi
    # restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://admin:admin@mongodb:27017
